### ISSUE TITLE
Dead link to *Git and versioning* in *function pool.fallback_folder()* info

### ISSUE THREAD

**Issue by JdenHartog** [smathot/osdoc#75]
On 
http://osdoc.cogsci.nl/3.1/manual/python/pool/#function-pool46fallback95folder4041
The link **versioning system** to 
http://osdoc.cogsci.nl/miscellaneous/git/
doesn't work.
Maybe link to
http://osdoc.cogsci.nl/3.0/miscellaneous/git/
or port http://osdoc.cogsci.nl/3.0/miscellaneous/git/ to 3.1

**Comment by smathot** [comment]
Thanks! This docstring was actually in the OpenSesame source code, so I fixed it there.
