### ISSUE TITLE
Installation for Ubuntu calls for package that does not exist

### ISSUE THREAD

**Issue by ajwills72** [smathot/osdoc#84]
sudo apt-get install gnome-icon-theme-full

returns:

sudo apt-get install gnome-icon-theme-full

On Ubuntu 18.04.

**Comment by smathot** [comment]
The tip to install `gnome-icon-theme-full` is for users who experience missing icons, which happened on older versions of Ubuntu. Do you mean that you also experience missing icons on Ubuntu 18.04, but that you need to install a different package?

**Comment by ajwills72** [comment]
Ah, OK. Perhaps then specify the version (e.g. for Ubuntu < 18.04)? No, I didn't install another package. As far as I'm aware I don't have icons missing, but as I'm new to the software, I wasn't confident I would be able to diagnose missing icons over any other issue I might or might not encounter, so felt it was safer to do the suggested install anyway.

**Comment by ajwills72** [comment]
The problem in Ubuntu 18.04 is that trying to install that gnome-icon-theme-full package generates an error, because it no longer exists in 18.04.

**Comment by smathot** [comment]
Thanks for the feedback! I've clarified this along with a few other things.
