### ISSUE TITLE
Questions about formulation

### ISSUE THREAD

**Issue by patrickshas** [smathot/osdoc#94]
Can you explain where the "0.5" value in your deg-per-pixel formulation comes from? 
Thanks in advance

**Comment by smathot** [comment]
I'm assuming you're referring to this bit:

```
deg_per_px = degrees(atan2(.5 * h, d)) / (.5 * r)
```

Here, `h` and `r` refer to the full height (in cm) and vertical resolution (in pixels). However, we're interested in the height and resolution relative to the center, which is why these are divided by 2.
